### ISSUE TITLE
Flash memory address for Credentials and flash mode for NodeMCU

### ISSUE THREAD

**Issue by superuser789** [hrvach/espple#2]
Great Project.

In README.md , Flash memory address to write file 'wifi_credentials.bin' is 0x3FC00.
But in Makefile , the address mentioned to write credentials is 0x3c000.
Which is the correct address ?

I have NodeMCU ESP8266  board.  Which  flash_mode should I use  dio or qio ?

Thanks.

**Comment by hrvach** [comment]
Thanks a lot for catching this mistake, please use 0x3c000. The whole command is in the Makefile and you can check there.

I have only one ESP8266 board a friend gave to me, so I did not try various flavors. If you end up in a reboot loop with the blue led flashing, try --flash_mode dio and see if there is any difference. 

I'll do all I can to help you get it working, no problem.

**Comment by superuser789** [comment]
Flash mode dio worked for NodeMCU ESP8266 board.
I have $ symbol in my wifi password. It does not connect to my wifi access point.
It connects to wifi access point having password without any special character.

Thanks.

**Comment by hrvach** [comment]
I never thought of that, you're right - the dollar sign gets eaten.

Try it like this: `make credentials ssid='my ssid' password='thi$$ismypassword' `

The single quotes and two dollars should do the trick :-)

**Comment by superuser789** [comment]
Using two dollars does not work.
Working fine for alphanumeric password.

Can esp8266 be used to broadcast video signals ? (like streaming video to my TV wirelessly)
If not ?  Why is that so?
Can esp32 be used for that purpose ?

Thanks.

**Comment by hrvach** [comment]
I've tried with single quotes and a dollar sign, worked in my case. Does this work for you (escaping the $ with a backslash)?

`
python -c "open('wifi_credentials.bin', 'wb').write(''.join(i.ljust(32, '\0') for i in ['yourssid','yourpas\$word']))"
`
and then flashing the credentials:

`esptool write_flash 0x3c000 wifi_credentials.bin` 

I don't think ESP8266 could do broadcasting video because it is short on memory. A 720x576 video frame needs to display 414720 pixels on the screen, each pixel would be represented with 3 bytes (1 for red, green or blue).  That would require 1,2 MB of memory, while the ESP has only 96 kB total.  ESP32 has 560 kB, still falls short. If it had more memory, maybe it could be done.
